sculpin_content_types:
    posts:
        permalink: :year/:month/:day/:filename/
services:
    wyrihaximus.html_compress.compress:
        class: \WyriHaximus\HtmlCompress\Frameworks\SculpinListener
        tags:
            - {  name: kernel.event_listener, event: sculpin.core.after_format, method: onAfterFormatSmallest }
