title: MageCode
subtitle: Taming Magento.
breakpoint: "<!-- break -->"
author:
    name: Nikita Chernyi
    url: https://about.me/nikus

services:
    facebook: "magecode.xyz"
    medium: "nikus"
    twitter: "magecode_xyz"
    disqus: "magecode"
    ganalytics: "UA-66233712-1"
    adsense:
        enabled: true
        content:
            id: "ca-pub-5549091042676165"
            skyscraper: "2814305939"
            adaptive: "1794584335"
